---
abstract: 'Command-line interface to GDAX / Coinbase Pro'
author:
  - 'Josh Rabinowitz <joshr@joshr.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Finance-CoinbasePro-API-CLI
no_index:
  directory:
    - t
    - inc
requires:
  Config::INI: '0'
  Data::Dump: '0'
  Date::Parse: '0'
  File::HomeDir: '0'
  Finance::GDAX::API: '0.09'
  FindBin: '0'
  JSON: '0'
  List::Util: '0'
  Mouse: '0'
  Number::Format: '0'
  Pod::Autopod: '0'
  Time::Moment: '0'
version: 0.000_01
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
